add section+modal (mobile)
Mykola1612/project-team-9 pull request #19
Opened 2023-06-18 20:22 UTC by Volodumur07

2023-06-18 20:48 UTC, Mykola1612 requested changes

2023-06-18 20:48 UTC, Mykola1612 commented on src/partials/subscribe.html
js підключи в папку main.js там є приклади підключення використовуй властивість import. а із  html сторінки видали тег script

2023-06-18 21:31 UTC, KaloRem approved these changes
Єдине то те що Микола зауважив, це по його стороні компетентно.
Супер робота!

2023-06-19 17:45 UTC, Mykola1612 approved these changes

2023-06-19 17:46 UTC, merged